# Basic
title: Collacat的博客
subtitle: 花有重开日，人无在少年
welcome_message: welcome!
description: 嗨，我是Collacat
creator: <a href="https://onev.cat">@onevcat</a>

url: "https://onevcat.com"

permalink: /:year/:month/:title/

#Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: '//onev.cat'}
    - {title: 工具, description: 我所使用的 app 们, url: '/apps'}
    - {title: 订阅, description: 邮件订阅本站, url: '//objccn.io/subscribe'}

# Pagination
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

# Comment
#comment:
#    disqus: onevcat
    #duoshuo
#Social
#social:
#    weibo: onevcat
 #   github: onevcat
  #  twitter: onevcat
   # gplus: 107108267983477358170
    #mail: onev@onevcat.com


